### ISSUE TITLE
How the "camera-facing billboards" works

### ISSUE THREAD

**Issue by OBKF** [dbp8890/LineRenderer#1]
Hi, and thank you for your work.
So I am making a trail renderer pluging and the only thing keeping it unreleased is the  camera-facing billboarding (I failed to make that work property) and tiled texture(not implemented yet but this one is easy).
Can you explain or direct me to the part where this is done?

**Comment by OBKF** [comment]
OK, GOT IT :tada: 

```
var AB = B - A;
var orthogonalABStart = (cameraOrigin - ((A + B) / 2)).cross(AB).normalized()
```

That was easy :)

**Comment by dbp8890** [comment]
Sorry for the (really) late reply! Glad this could be helpful; nice job on the latest trail plugin!

**Comment by OBKF** [comment]
@dbp8890 No worries, it actually took me a year to find this, you saved the project literally.
